package ai.pipestream.grpc.gatherer.it;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.transport.RefSpec;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.FileDescriptorSet;

class GatherProtosTaskIntegrationTest {

    @TempDir
    Path tempDir;

    @Test
    void filesystemSourceAndDescriptorRoutingAreWiredEndToEnd() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();
        BuildResult result = runBuild(projectDir, "build");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":gatherProtos"));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/grpc/health/v1/health.proto")));

        Path generatedBytecodeJar = projectDir.resolve("build/quarkus-app/quarkus/generated-bytecode.jar");
        assertTrue(Files.exists(generatedBytecodeJar), "Expected generated bytecode jar at " + generatedBytecodeJar);

        try (ZipFile zipFile = new ZipFile(generatedBytecodeJar.toFile())) {
            ZipEntry descriptorEntry = zipFile.getEntry("META-INF/grpc/services.dsc");
            assertNotNull(descriptorEntry, "generated-bytecode.jar must contain META-INF/grpc/services.dsc");

            FileDescriptorSet set = FileDescriptorSet.parseFrom(zipFile.getInputStream(descriptorEntry).readAllBytes());
            Set<String> files = set.getFileList().stream()
                    .map(FileDescriptorProto::getName)
                    .collect(Collectors.toSet());
            Set<String> services = set.getFileList().stream()
                    .flatMap(f -> f.getServiceList().stream().map(s -> f.getPackage() + "." + s.getName()))
                    .collect(Collectors.toSet());

            assertTrue(files.stream().anyMatch(f -> f.endsWith("schemas/common.proto")),
                    "descriptor set must include schemas/common.proto; found files: " + files);
            assertTrue(files.stream().anyMatch(f -> f.endsWith("grpc/health/v1/health.proto")),
                    "descriptor set must include grpc/health/v1/health.proto; found files: " + files);
            assertTrue(services.contains("grpc.health.v1.Health"),
                    "descriptor set must include grpc.health.v1.Health; found services: " + services);
        }
    }

    @Test
    void gatherProtosIsUpToDateOnSecondBuild() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();

        BuildResult first = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(first, ":gatherProtos"));

        BuildResult second = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.UP_TO_DATE, taskOutcome(second, ":gatherProtos"));
    }

    @Test
    void changingProtoTriggersRebuild() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();

        BuildResult first = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(first, ":gatherProtos"));

        Path commonProto = projectDir.resolve("test-protos/schemas/common.proto");
        Files.writeString(commonProto, Files.readString(commonProto) + "\n// changed");

        BuildResult second = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(second, ":gatherProtos"));
        assertTrue(Files.readString(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")).contains("changed"));
    }

    @Test
    void cleanBuildRecreatesGatheredOutput() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();

        BuildResult initial = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(initial, ":gatherProtos"));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")));

        BuildResult cleanBuild = runBuild(projectDir, "clean", "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(cleanBuild, ":gatherProtos"));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/grpc/health/v1/health.proto")));
    }

    @Test
    void bufWorkspaceFromLocalBareRepoStagesModulesAndPopulatesCache() throws Exception {
        Path projectDir = prepareSampleProject("testkit-sample");
        Path gradleUserHome = projectDir.resolve("gradle-home");
        String repoUri = createLocalBareBufWorkspaceRepo();

        String buildFile = Files.readString(projectDir.resolve("build.gradle"))
                .replace("filesystem {\n        dirs.from(file('test-protos'))\n    }", """
                        bufWorkspace {
                            repo = '%s'
                            ref = 'main'
                            modules = ['common', 'pipeline-module']
                            protoSubdir = 'proto'
                        }
                        """.formatted(repoUri));
        Files.writeString(projectDir.resolve("build.gradle"), buildFile);

        BuildResult result = runBuild(projectDir, gradleUserHome, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":gatherProtos"));

        Set<String> gatheredFiles;
        try (var paths = Files.walk(projectDir.resolve("build/gathered-protos/proto"))) {
            gatheredFiles = paths.filter(Files::isRegularFile)
                    .map(path -> projectDir.resolve("build/gathered-protos/proto").relativize(path).toString().replace('\\', '/'))
                    .collect(Collectors.toCollection(HashSet::new));
        }
        assertTrue(gatheredFiles.stream().anyMatch(path -> path.endsWith("example/common/v1/common.proto")),
                "Expected common module proto in gathered output, found: " + gatheredFiles);
        assertTrue(gatheredFiles.stream().anyMatch(path -> path.endsWith("example/pipeline/v1/pipeline.proto")),
                "Expected pipeline module proto in gathered output, found: " + gatheredFiles);

        Path cacheRoot = gradleUserHome.resolve("caches/grpc-gatherer");
        assertTrue(Files.isDirectory(cacheRoot), "Expected clone cache root at " + cacheRoot);
        try (var paths = Files.list(cacheRoot)) {
            assertTrue(paths.findAny().isPresent(), "Expected at least one cache entry under " + cacheRoot);
        }
    }

    private Path prepareFilesystemSampleProject() throws Exception {
        Path projectDir = prepareSampleProject("testkit-sample");
        copyResourceTree("fixtures", projectDir.resolve("test-protos"));
        return projectDir;
    }

    private Path prepareSampleProject(String resourceDir) throws Exception {
        Path target = tempDir.resolve(resourceDir);
        copyResourceTree(resourceDir, target);

        String rootPath = repositoryRoot().toString().replace("\\", "/");
        Path settingsFile = target.resolve("settings.gradle");
        Files.writeString(settingsFile,
                Files.readString(settingsFile).replace("__REPO_ROOT__", rootPath));

        return target;
    }

    private void copyResourceTree(String resourceDir, Path destination) throws Exception {
        URI sourceUri = GatherProtosTaskIntegrationTest.class.getClassLoader().getResource(resourceDir).toURI();
        // Path.of(uri) works when test resources are extracted to disk (Gradle test runtime).
        // Runners that serve test resources from a jar may fail here with FileSystemNotFoundException.
        Path source = Path.of(sourceUri);
        try (var stream = Files.walk(source)) {
            for (Path path : stream.toList()) {
                Path relative = source.relativize(path);
                Path target = destination.resolve(relative.toString());
                if (Files.isDirectory(path)) {
                    Files.createDirectories(target);
                } else {
                    Files.createDirectories(target.getParent());
                    Files.copy(path, target, StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }
    }

    private BuildResult runBuild(Path projectDir, String... tasks) {
        return runBuild(projectDir, projectDir.resolve("gradle-home"), tasks);
    }

    private BuildResult runBuild(Path projectDir, Path gradleUserHome, String... tasks) {
        String[] args = new String[tasks.length + 4];
        args[0] = "-g";
        args[1] = gradleUserHome.toString();
        args[2] = "--console=plain";
        args[3] = "--stacktrace";
        System.arraycopy(tasks, 0, args, 4, tasks.length);

        return GradleRunner.create()
                .withProjectDir(projectDir.toFile())
                .withArguments(Arrays.asList(args))
                .build();
    }

    private TaskOutcome taskOutcome(BuildResult result, String taskPath) {
        return result.task(taskPath).getOutcome();
    }

    private Path repositoryRoot() {
        Path userDir = Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
        if (Files.isDirectory(userDir.resolve("integration-tests"))) {
            return userDir;
        }
        if (userDir.getFileName() != null && "integration-tests".equals(userDir.getFileName().toString())) {
            return userDir.getParent();
        }
        throw new IllegalStateException("Cannot resolve repository root from " + userDir);
    }

    private String createLocalBareBufWorkspaceRepo() throws Exception {
        Path remoteBare = tempDir.resolve("buf-remote.git");
        Path working = tempDir.resolve("buf-work");

        try (Git bare = Git.init().setBare(true).setDirectory(remoteBare.toFile()).call();
                Git work = Git.init().setInitialBranch("main").setDirectory(working.toFile()).call()) {
            Files.createDirectories(working.resolve("common/proto/example/common/v1"));
            Files.createDirectories(working.resolve("pipeline-module/proto/example/pipeline/v1"));

            Files.writeString(working.resolve("common/proto/example/common/v1/common.proto"), """
                    syntax = "proto3";
                    package example.common.v1;

                    message Common {
                      string id = 1;
                    }
                    """);
            Files.writeString(working.resolve("pipeline-module/proto/example/pipeline/v1/pipeline.proto"), """
                    syntax = "proto3";
                    package example.pipeline.v1;

                    import "example/common/v1/common.proto";

                    message Pipeline {
                      example.common.v1.Common common = 1;
                    }
                    """);

            work.add().addFilepattern(".").call();
            work.commit().setMessage("initial").call();
            work.remoteAdd().setName("origin").setUri(new org.eclipse.jgit.transport.URIish(remoteBare.toUri().toString())).call();
            work.push().setRemote("origin").setRefSpecs(new RefSpec("refs/heads/main:refs/heads/main")).call();
            bare.getRepository().updateRef("HEAD").link("refs/heads/main");
        }

        return remoteBare.toUri().toString();
    }
}
