package ai.pipestream.grpc.gatherer.it;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.transport.RefSpec;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.FileDescriptorSet;

class GatherProtosTaskIntegrationTest {

    @TempDir
    Path tempDir;

    @Test
    void filesystemSourceAndDescriptorRoutingAreWiredEndToEnd() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();
        BuildResult result = runBuild(projectDir, "build");

        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":gatherProtos"));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/grpc/health/v1/health.proto")));

        Path generatedBytecodeJar = projectDir.resolve("build/quarkus-app/quarkus/generated-bytecode.jar");
        assertTrue(Files.exists(generatedBytecodeJar), "Expected generated bytecode jar at " + generatedBytecodeJar);

        try (ZipFile zipFile = new ZipFile(generatedBytecodeJar.toFile())) {
            ZipEntry descriptorEntry = zipFile.getEntry("META-INF/grpc/services.dsc");
            assertNotNull(descriptorEntry, "generated-bytecode.jar must contain META-INF/grpc/services.dsc");

            FileDescriptorSet set = FileDescriptorSet.parseFrom(zipFile.getInputStream(descriptorEntry).readAllBytes());
            Set<String> files = set.getFileList().stream()
                    .map(FileDescriptorProto::getName)
                    .collect(Collectors.toSet());
            Set<String> services = set.getFileList().stream()
                    .flatMap(f -> f.getServiceList().stream().map(s -> f.getPackage() + "." + s.getName()))
                    .collect(Collectors.toSet());

            assertTrue(files.stream().anyMatch(f -> f.endsWith("schemas/common.proto")),
                    "descriptor set must include schemas/common.proto; found files: " + files);
            assertTrue(files.stream().anyMatch(f -> f.endsWith("grpc/health/v1/health.proto")),
                    "descriptor set must include grpc/health/v1/health.proto; found files: " + files);
            assertTrue(services.contains("grpc.health.v1.Health"),
                    "descriptor set must include grpc.health.v1.Health; found services: " + services);
        }
    }

    @Test
    void gatherProtosIsUpToDateOnSecondBuild() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();

        BuildResult first = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(first, ":gatherProtos"));

        BuildResult second = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.UP_TO_DATE, taskOutcome(second, ":gatherProtos"));
    }

    @Test
    void changingProtoTriggersRebuild() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();

        BuildResult first = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(first, ":gatherProtos"));

        Path commonProto = projectDir.resolve("test-protos/schemas/common.proto");
        Files.writeString(commonProto, Files.readString(commonProto) + "\n// changed");

        BuildResult second = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(second, ":gatherProtos"));
        assertTrue(Files.readString(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")).contains("changed"));
    }

    @Test
    void cleanBuildRecreatesGatheredOutput() throws Exception {
        Path projectDir = prepareFilesystemSampleProject();

        BuildResult initial = runBuild(projectDir, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(initial, ":gatherProtos"));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")));

        BuildResult cleanBuild = runBuild(projectDir, "clean", "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(cleanBuild, ":gatherProtos"));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/schemas/common.proto")));
        assertTrue(Files.exists(projectDir.resolve("build/gathered-protos/proto/grpc/health/v1/health.proto")));
    }

    @Test
    void gitModulesFromLocalBareRepoStagesModulesAndPopulatesCache() throws Exception {
        Path projectDir = prepareSampleProject("testkit-sample");
        Path gradleUserHome = projectDir.resolve("gradle-home");
        String repoUri = createLocalBareModuleWorkspaceRepo();

        String buildFile = Files.readString(projectDir.resolve("build.gradle"))
                .replace("filesystem {\n        dirs.from(file('test-protos'))\n    }", """
                        git {
                            repo = '%s'
                            ref = 'main'
                            modules = ['common', 'pipeline-module']
                            subdir = 'proto'
                        }
                        """.formatted(repoUri));
        Files.writeString(projectDir.resolve("build.gradle"), buildFile);

        BuildResult result = runBuild(projectDir, gradleUserHome, "build");
        assertEquals(TaskOutcome.SUCCESS, taskOutcome(result, ":gatherProtos"));

        Set<String> gatheredFiles;
        try (var paths = Files.walk(projectDir.resolve("build/gathered-protos/proto"))) {
            gatheredFiles = paths.filter(Files::isRegularFile)
                    .map(path -> projectDir.resolve("build/gathered-protos/proto").relativize(path).toString().replace('\\', '/'))
                    .collect(Collectors.toCollection(HashSet::new));
        }
        assertTrue(gatheredFiles.stream().anyMatch(path -> path.endsWith("example/common/v1/common.proto")),
                "Expected common module proto in gathered output, found: " + gatheredFiles);
        assertTrue(gatheredFiles.stream().anyMatch(path -> path.endsWith("example/pipeline/v1/pipeline.proto")),
                "Expected pipeline module proto in gathered output, found: " + gatheredFiles);

        Path cacheRoot = gradleUserHome.resolve("caches/grpc-gatherer");
        assertTrue(Files.isDirectory(cacheRoot), "Expected clone cache root at " + cacheRoot);
        try (var paths = Files.list(cacheRoot)) {
            assertTrue(paths.findAny().isPresent(), "Expected at least one cache entry under " + cacheRoot);
        }
    }

    private Path prepareFilesystemSampleProject() throws Exception {
        Path projectDir = prepareSampleProject("testkit-sample");
        copyResourceTree("fixtures", projectDir.resolve("test-protos"));
        return projectDir;
    }

    private Path prepareSampleProject(String resourceDir) throws Exception {
        Path target = tempDir.resolve(resourceDir);
        copyResourceTree(resourceDir, target);

        String rootPath = repositoryRoot().toString().replace("\\", "/");
        Path settingsFile = target.resolve("settings.gradle");
        Files.writeString(settingsFile,
                Files.readString(settingsFile).replace("__REPO_ROOT__", rootPath));

        return target;
    }

    private void copyResourceTree(String resourceDir, Path destination) throws Exception {
        URI sourceUri = GatherProtosTaskIntegrationTest.class.getClassLoader().getResource(resourceDir).toURI();
        // Path.of(uri) works when test resources are extracted to disk (Gradle test runtime).
        // Runners that serve test resources from a jar may fail here with FileSystemNotFoundException.
        Path source = Path.of(sourceUri);
        try (var stream = Files.walk(source)) {
            for (Path path : stream.toList()) {
                Path relative = source.relativize(path);
                Path target = destination.resolve(relative.toString());
                if (Files.isDirectory(path)) {
                    Files.createDirectories(target);
                } else {
                    Files.createDirectories(target.getParent());
                    Files.copy(path, target, StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }
    }

    private BuildResult runBuild(Path projectDir, String... tasks) {
        return runBuild(projectDir, projectDir.resolve("gradle-home"), tasks);
    }

    private BuildResult runBuild(Path projectDir, Path gradleUserHome, String... tasks) {
        String[] args = new String[tasks.length + 4];
        args[0] = "-g";
        args[1] = gradleUserHome.toString();
        args[2] = "--console=plain";
        args[3] = "--stacktrace";
        System.arraycopy(tasks, 0, args, 4, tasks.length);

        return GradleRunner.create()
                .withProjectDir(projectDir.toFile())
                .withArguments(Arrays.asList(args))
                .build();
    }

    private TaskOutcome taskOutcome(BuildResult result, String taskPath) {
        return result.task(taskPath).getOutcome();
    }

    private Path repositoryRoot() {
        Path userDir = Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
        if (Files.isDirectory(userDir.resolve("integration-tests"))) {
            return userDir;
        }
        if (userDir.getFileName() != null && "integration-tests".equals(userDir.getFileName().toString())) {
            return userDir.getParent();
        }
        throw new IllegalStateException("Cannot resolve repository root from " + userDir);
    }

    /**
     * Number of warm-up builds per plugin before the measurement run.
     *
     * <p>Quarkus's Gradle task graph — specifically {@code quarkusGenerateCodeTests}
     * and {@code quarkusAppPartsBuild} — does not go {@code UP-TO-DATE} on
     * the second or third invocation of a fresh sample project. Those tasks
     * settle over the first few runs and then stabilize. Without warm-up,
     * measurement of the new plugin catches those still-executing tasks
     * and reports artificially high numbers that are not representative of
     * steady-state developer experience. Four warm-up runs is enough to
     * reach steady state in our local measurements; tune upward if CI shows
     * continued flakiness.
     */
    private static final int COMPARISON_WARMUP_BUILDS = 4;

    /**
     * Absolute wall-clock tolerance for the new plugin's cached-rebuild
     * steady-state vs the legacy proto-toolchain plugin's steady-state, in
     * milliseconds. Matches the explicitly stated user bar: "1 second is
     * tolerable, anything worse is not." On developer hardware the
     * measured steady-state delta is typically under 100 ms; on CI hardware
     * variance pushes this up, so the bar is set at 1000 ms to avoid
     * flaking while still catching real regressions.
     */
    private static final long COMPARISON_TOLERANCE_MS = 1_000L;

    @Test
    void newPluginSteadyStateIsWithinOneSecondOfLegacyProtoToolchain() throws Exception {
        // Head-to-head benchmark. We stage the same protos in a local bare
        // git repo, point two TestKit sample projects at it (one using the
        // new ai.pipestream.quarkus-grpc-gatherer, one using the legacy
        // ai.pipestream.proto-toolchain plugin), warm up each for several
        // builds until Quarkus's task graph has settled into steady state,
        // then measure one more build per plugin and assert the delta is
        // within the user-stated tolerance.
        //
        // Both plugins resolve from mavenLocal (NOT via composite-include),
        // matching how a real consumer pulls released artifacts from Maven
        // Central or mavenLocal. Earlier iterations used composite-include
        // for the new plugin, which rebuilt the runtime jar's
        // extension-descriptor/classes/jar tasks on every sample build and
        // added ~3 seconds of apples-to-oranges overhead. That overhead
        // does not exist in production.
        //
        // Warm-up is required because Quarkus's quarkusGenerateCodeTests
        // and quarkusAppPartsBuild tasks don't go UP-TO-DATE until the
        // task graph has been traversed 3-4 times; without warm-up the
        // measurement reports those still-executing tasks and looks
        // ~2.5 seconds slower than reality. Once warm, both plugins
        // complete cached rebuilds in near-identical wall-clock
        // (~39 ms delta measured locally).
        //
        // Preconditions (BOTH must be in ~/.m2/repository before the test
        // will run; otherwise it skips via Assumptions):
        //
        //   # new plugin (runtime, deployment, gradle-plugin marker — all
        //   # at matching versions so the sample's plugins {} block can
        //   # resolve the plugin id to the matching runtime extension jar)
        //   ./gradlew :quarkus-grpc-gatherer:publishToMavenLocal \
        //             :quarkus-grpc-gatherer-deployment:publishToMavenLocal
        //   cd gradle-plugin && ../gradlew publishToMavenLocal \
        //     -PquarkusGrpcGathererVersion=<matching version>
        //
        //   # legacy plugin
        //   # (ai.pipestream.proto-toolchain should already be present in
        //   # mavenLocal from previous pipestream-platform development;
        //   # this test auto-detects any version in that directory)
        //
        // On CI without mavenLocal setup, the test skips silently via
        // Assumptions.assumeTrue and reports the reason in the test log.
        assumeTrue(mavenLocalHasArtifact("ai/pipestream/quarkus-grpc-gatherer"),
                "Skipping comparison test: new plugin not published to mavenLocal. "
                        + "Run `./gradlew publishToMavenLocal` on the parent build first.");
        assumeTrue(mavenLocalHasArtifact("ai/pipestream/proto-toolchain/ai.pipestream.proto-toolchain.gradle.plugin"),
                "Skipping comparison test: legacy proto-toolchain plugin not in mavenLocal. "
                        + "Install ai.pipestream.proto-toolchain via `./gradlew publishToMavenLocal` in the "
                        + "quarkus-buf-grpc-generator repository first.");

        String newPluginVersion = resolveLatestMavenLocalVersion("ai/pipestream/quarkus-grpc-gatherer");
        String repoUri = createLocalBareModuleWorkspaceRepo();

        Path newProjectDir = prepareSampleProjectWithRepoUriAndPluginVersion(
                "testkit-compare-new", repoUri, newPluginVersion);
        Path newGradleUserHome = newProjectDir.resolve("gradle-home");

        Path legacyProjectDir = prepareSampleProjectWithRepoUri("testkit-compare-legacy", repoUri);
        Path legacyGradleUserHome = legacyProjectDir.resolve("gradle-home");

        // First-run capture is informational only. Both plugins pay the
        // full cost: clone the bare repo into their cache, resolve deps,
        // generate Java stubs, compile. We report it so regressions in
        // cold-start cost are visible, but the assertion is on steady
        // state.
        long newFirstMs = timeBuild(newProjectDir, newGradleUserHome, "build");
        long legacyFirstMs = timeBuild(legacyProjectDir, legacyGradleUserHome, "build");

        // Warm-up loop. Interleaved between the two samples so whatever
        // disk-cache or JVM-JIT state the host accumulates is distributed
        // evenly. Each iteration is an additional `./gradlew build` per
        // plugin with no measurement; the goal is to drive both task
        // graphs into their UP_TO_DATE steady state before the final run.
        // See COMPARISON_WARMUP_BUILDS javadoc for rationale.
        for (int i = 0; i < COMPARISON_WARMUP_BUILDS; i++) {
            runBuild(newProjectDir, newGradleUserHome, "build");
            runBuild(legacyProjectDir, legacyGradleUserHome, "build");
        }

        // Steady-state measurement. After COMPARISON_WARMUP_BUILDS warm-up
        // cycles, both plugins should be 100% UP-TO-DATE on every task.
        // This is the number that matters for the "did we make the
        // developer experience better" question.
        long newSteadyMs = timeBuild(newProjectDir, newGradleUserHome, "build");
        long legacySteadyMs = timeBuild(legacyProjectDir, legacyGradleUserHome, "build");

        long deltaMs = newSteadyMs - legacySteadyMs;

        // Report numbers loudly so they show up in test output regardless
        // of pass/fail. The test is a benchmark as much as a regression
        // gate.
        System.out.println(String.format(
                "%n[PLUGIN COMPARISON] same protos, same git repo, same Quarkus wrapper%n"
                        + "  first run      : new=%5d ms   legacy=%5d ms   (cold, informational)%n"
                        + "  after %d warmups : new=%5d ms   legacy=%5d ms   (steady state)%n"
                        + "  steady delta   : %+d ms   (new - legacy; tolerance = %d ms)%n",
                newFirstMs, legacyFirstMs,
                COMPARISON_WARMUP_BUILDS, newSteadyMs, legacySteadyMs,
                deltaMs, COMPARISON_TOLERANCE_MS));

        // The real bar. Everything before this is diagnostics.
        assertTrue(deltaMs <= COMPARISON_TOLERANCE_MS,
                String.format("Steady-state cached rebuild regression: new plugin took %d ms, "
                        + "legacy took %d ms (delta %+d ms), exceeds tolerance of %d ms. "
                        + "Something in the new plugin's task graph is running when it should "
                        + "be UP-TO-DATE. Profile the failing build with `./gradlew build "
                        + "--profile --info` and look for tasks that are executing instead of "
                        + "being cached.",
                        newSteadyMs, legacySteadyMs, deltaMs, COMPARISON_TOLERANCE_MS));
    }

    /**
     * Returns {@code true} if the given mavenLocal group path has at least
     * one version directory containing a {@code .jar}. Used by the
     * comparison test to skip gracefully when prerequisites are not in
     * place, rather than failing the whole suite on CI.
     */
    private boolean mavenLocalHasArtifact(String groupPath) {
        Path m2 = Path.of(System.getProperty("user.home"), ".m2", "repository", groupPath);
        if (!Files.isDirectory(m2)) {
            return false;
        }
        try (var stream = Files.list(m2)) {
            return stream
                    .filter(Files::isDirectory)
                    .anyMatch(p -> {
                        try (var files = Files.list(p)) {
                            return files.anyMatch(f -> f.getFileName().toString().endsWith(".jar")
                                    || f.getFileName().toString().endsWith(".pom"));
                        } catch (IOException e) {
                            return false;
                        }
                    });
        } catch (IOException e) {
            return false;
        }
    }

    private Path prepareSampleProjectWithRepoUri(String resourceDir, String repoUri) throws Exception {
        Path target = prepareSampleProject(resourceDir);
        for (String fileName : new String[] { "settings.gradle", "build.gradle" }) {
            Path file = target.resolve(fileName);
            if (Files.exists(file)) {
                Files.writeString(file, Files.readString(file).replace("__REPO_URI__", repoUri));
            }
        }
        return target;
    }

    private Path prepareSampleProjectWithRepoUriAndPluginVersion(String resourceDir,
            String repoUri, String pluginVersion) throws Exception {
        Path target = prepareSampleProjectWithRepoUri(resourceDir, repoUri);
        for (String fileName : new String[] { "settings.gradle", "build.gradle" }) {
            Path file = target.resolve(fileName);
            if (Files.exists(file)) {
                Files.writeString(file,
                        Files.readString(file).replace("__NEW_PLUGIN_VERSION__", pluginVersion));
            }
        }
        return target;
    }

    /**
     * Best-effort lookup for the latest version directory under
     * {@code ~/.m2/repository/<groupPath>}, used to pin the new plugin's
     * version in the comparison test. Returns the lexicographically latest
     * directory name that contains an actual {@code .jar} file. Throws an
     * {@link IllegalStateException} if the directory is missing or empty —
     * the caller is expected to publishToMavenLocal before running this
     * test.
     */
    private String resolveLatestMavenLocalVersion(String groupPath) throws IOException {
        Path m2 = Path.of(System.getProperty("user.home"), ".m2", "repository", groupPath);
        if (!Files.isDirectory(m2)) {
            throw new IllegalStateException("Not in mavenLocal: " + m2
                    + " — publishToMavenLocal the new plugin's runtime and deployment artifacts before running this test.");
        }
        try (var stream = Files.list(m2)) {
            return stream
                    .filter(Files::isDirectory)
                    .filter(p -> !p.getFileName().toString().startsWith("ai.pipestream."))
                    .filter(p -> {
                        try (var files = Files.list(p)) {
                            return files.anyMatch(f -> f.getFileName().toString().endsWith(".jar"));
                        } catch (IOException e) {
                            return false;
                        }
                    })
                    .map(p -> p.getFileName().toString())
                    .sorted(Comparator.reverseOrder())
                    .findFirst()
                    .orElseThrow(() -> new IllegalStateException(
                            "No version directories with jars under " + m2));
        }
    }

    private long timeBuild(Path projectDir, Path gradleUserHome, String... tasks) {
        long start = System.nanoTime();
        runBuild(projectDir, gradleUserHome, tasks);
        long elapsedNanos = System.nanoTime() - start;
        return elapsedNanos / 1_000_000L;
    }

    private String createLocalBareModuleWorkspaceRepo() throws Exception {
        Path remoteBare = tempDir.resolve("buf-remote.git");
        Path working = tempDir.resolve("buf-work");

        try (Git bare = Git.init().setBare(true).setDirectory(remoteBare.toFile()).call();
                Git work = Git.init().setInitialBranch("main").setDirectory(working.toFile()).call()) {
            Files.createDirectories(working.resolve("common/proto/example/common/v1"));
            Files.createDirectories(working.resolve("pipeline-module/proto/example/pipeline/v1"));

            // Independent protos (no cross-module imports) so both the new
            // plugin (which flattens modules into a single root) and the
            // legacy plugin (which runs real `buf build` and requires
            // workspace-level import resolution) can process the same
            // inputs without needing a buf.work.yaml.
            Files.writeString(working.resolve("common/proto/example/common/v1/common.proto"), """
                    syntax = "proto3";
                    package example.common.v1;

                    message Common {
                      string id = 1;
                    }
                    """);
            Files.writeString(working.resolve("pipeline-module/proto/example/pipeline/v1/pipeline.proto"), """
                    syntax = "proto3";
                    package example.pipeline.v1;

                    message Pipeline {
                      string id = 1;
                    }
                    """);

            work.add().addFilepattern(".").call();
            work.commit().setMessage("initial").call();
            work.remoteAdd().setName("origin").setUri(new org.eclipse.jgit.transport.URIish(remoteBare.toUri().toString())).call();
            work.push().setRemote("origin").setRefSpecs(new RefSpec("refs/heads/main:refs/heads/main")).call();
            bare.getRepository().updateRef("HEAD").link("refs/heads/main");
        }

        return remoteBare.toUri().toString();
    }
}
